[package]
name = "bmd"
version = "0.1.0"
authors = ["Erin Moon <erin@hashbang.sh>"]
edition = '2018'

[dependencies]
byteorder = "1.2"
quick-error = "1.2"
indextree = "2.1"
num-derive = "0.2"
num-traits = "0.2"